### PR TITLE
Methods for mapping Wikipedia ID (Page ID) to Wikipedia page title and back (tests included)

### PR DESCRIPTION
**Pull request by Goader**

### CODE REVIEW

**Comment by Goader** [comment]
This is a continuation to the previous PR #14 

Sorry for bringing previous changes here too, but it should be alright to merge after the previous one :)

**Comment by jcklie** [comment]
I merged the other and now this one has conflicts, can you maybe fix them?

**Comment by Goader** [comment]
Ready for merge :wink:

**Comment by jcklie** [comment]
Thanks!

**Comment by jcklie** [comment]
I released 0.2.0 with your changes, I hope it works.

**Pull request merged**
